# application.yml

spring:
  application:
    name: product-service
#  cloud:
#    gateway:
#      default-filters:
#        - name: GlobalFilter
#          args:
#            baseMessage: Hello Spring Cloud Gateway Global Filter
#            preLogger: true
#            postLogger: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/